services:
  - type: web
    name: jccbuzz
    env: node
    buildCommand: pnpm install && node setup.js
    startCommand: node startForRender.js
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        value: mongodb+srv://darshilaggarwal11:UbQoLdX99DmR21S1@cluster0.w9kvi8i.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 